# Generated by Django 4.2 on 2023-04-28 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='地区')),
            ],
            options={
                'verbose_name': '影片发行地区',
                'verbose_name_plural': '影片发行地区',
                'db_table': 'df_film_region',
            },
        ),
        migrations.CreateModel(
            name='FilmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='种类名称')),
            ],
            options={
                'verbose_name': '影片类型',
                'verbose_name_plural': '影片类型',
                'db_table': 'df_film_type',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='电影名称')),
                ('score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='评分')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('actor', models.CharField(max_length=2000, verbose_name='主要演员')),
                ('production', models.CharField(max_length=100, verbose_name='制片国家或地区')),
                ('year', models.CharField(max_length=10, verbose_name='年代')),
                ('description', models.CharField(max_length=2000, verbose_name='简介')),
                ('poster', models.ImageField(upload_to='film', verbose_name='电影海报')),
                ('video', models.FileField(upload_to='video', verbose_name='片源')),
                ('film_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.filmregion', verbose_name='地区')),
                ('film_type', models.ManyToManyField(to='film.filmtype', verbose_name='电影类型')),
            ],
            options={
                'verbose_name': '影片',
                'verbose_name_plural': '影片',
                'db_table': 'df_film',
            },
        ),
    ]
