# Generated by Django 4.2 on 2023-04-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='video',
        ),
    ]
