# Generated by Django 4.2 on 2023-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_remove_film_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='评分'),
        ),
    ]
