# Generated by Django 4.2 on 2023-05-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_alter_film_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.filmregion', verbose_name='地区'),
        ),
    ]
