# Generated by Django 4.2 on 2023-05-10 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_film_create_time_film_is_delete_film_update_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmSPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '影片SPU',
                'verbose_name_plural': '影片SPU',
                'db_table': 'df_film_spu',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='spu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.filmspu', verbose_name='影片SPU'),
        ),
    ]
