# Generated by Django 4.2 on 2023-05-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_filmspu_film_spu'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(default=None, upload_to='video', verbose_name='片源'),
        ),
    ]
