# Generated by Django 4.2 on 2023-05-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_film_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='影片播放数'),
        ),
    ]
