# Generated by Django 4.2 on 2023-05-28 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_film_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexFilmsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('poster', models.ImageField(upload_to='banner', verbose_name='电影海报')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('film', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='film.film', verbose_name='电影名称')),
            ],
            options={
                'verbose_name': '首页轮播影片',
                'verbose_name_plural': '首页轮播影片',
                'db_table': 'df_ind_films_banner',
            },
        ),
    ]
